import Config

# Configure your database
config :comcent, Comcent.Repo,
  username: "postgres",
  password: "password",
  hostname: "postgres",
  database: "postgres",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  types: Comcent.PostgrexTypes

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :comcent, ComcentWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Kus3yRx9kiZjpJX4oOD2VrT05GMB2U/wPstXsxAVccU0QGy0AY/mjQPhS2x7EyVw",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :comcent, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message $metadata\n", metadata: [:mfa]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :libcluster,
  topologies: [
    gossip: [
      strategy: Cluster.Strategy.Gossip
    ]
  ]

config :comcent, Comcent.Schedular,
  jobs: [
    # NOTE: We are noting running any jobs in dev. Uncomment when necessary to test
    # Test job that runs every minute
    # test_job: [
    #   schedule: "* * * * *",
    #   task: fn ->
    #     current_time = DateTime.utc_now() |> DateTime.to_string()
    #     current_node = Node.self() |> to_string()

    #     IO.puts(
    #       "**** #{current_time} - This is a test message from the scheduler on node #{current_node} ****"
    #     )
    #   end,
    #   run_strategy: Quantum.RunStrategy.Local
    # ]
    # check_wallet_balance: [
    #   schedule: "0 9 * * *",
    #   task: {Comcent.EmailHandler, :check_and_send_alerts, []},
    #   run_strategy: Quantum.RunStrategy.Local
    # ],
    # monthly_billing: [
    #   # Run at midnight on the first day of each month
    #   schedule: "0 0 1 * *",
    #   task: {Comcent.MonthlyBilling, :process_monthly_billing, []},
    #   run_strategy: Quantum.RunStrategy.Local
    # ]
    # daily_summary: [
    #   # Run every minute for testing purposes
    #   schedule: "* * * * *",
    #   task: {Comcent.DailySummary, :generate_daily_summaries, []},
    #   run_strategy: Quantum.RunStrategy.Local
    # ],
    # daily_summary_fallback: [
    #   # Run every hour at minute 0
    #   schedule: "0 * * * *",
    #   task: {Comcent.DailySummary, :fallback_daily_summaries, []},
    #   run_strategy: Quantum.RunStrategy.Local
    # ]
  ]
